import z from "zod";
import type { FormField } from "../../components/custom";

export const addressSchema = z.object({
  country: z.string().min(1, "Country is required"),
  district: z.string().optional(),
  province: z.string().optional(),
  municipality: z.string().optional(),
  ward_no: z.number().optional(),
  google_map: z.string().optional(),
});

export const patientSchema = z.object({
  first_name: z.string().min(1, "First name is required"),
  last_name: z.string().min(1, "Last name is required"),
  middle_name: z.string().optional(),
  phone: z.string().min(1, "Primary Phone is required"),
  phone2: z.string().optional(),
  email: z.email("Invalid email").min(1, "Email is required"),
  gender: z.string().optional(),
  dob: z.string(),
  marital_status: z.string().optional(),
  status: z.string(),
  address: addressSchema.optional(),
});

export const patientFormFields: FormField[] = [
  {
    name: "first_name",
    label: "First Name",
    type: "text",
    placeholder: "Enter first name",
    required: true,
    gridCol: 2,
  },
  {
    name: "middle_name",
    label: "Middle Name",
    type: "text",
    placeholder: "Enter Middle name",
    required: false,
    gridCol: 2,
  },
  {
    name: "last_name",
    label: "Last Name",
    type: "text",
    placeholder: "Enter last name",
    required: true,
    gridCol: 2,
  },
  {
    name: "email",
    label: "Email Address",
    type: "email",
    placeholder: "Enter email",
    required: true,
    gridCol: 1,
  },
  {
    name: "phone",
    label: "Primary Phone",
    type: "text",
    placeholder: "Enter primary phone",
    required: true,
    gridCol: 2,
  },
  {
    name: "phone2",
    label: "Secondary Phone",
    type: "text",
    placeholder: "Enter secondary phone",
    required: false,
    gridCol: 2,
  },
  {
    name: "dob",
    label: "Date of Birth",
    type: "date",
    placeholder: "Enter date of birth",
    required: false,
    gridCol: 2,
  },
  {
    name: "gender",
    label: "Gender",
    type: "select",
    required: true,
    default: "male",
    gridCol: 2,
    options: [
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
      { label: "Others", value: "others" },
      { label: "Unknown", value: "unknown" },
    ],
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    required: true,
    default: "pending",
    gridCol: 2,
    options: [
      { label: "Pending", value: "pending" },
      { label: "Active", value: "active" },
      { label: "Inactive", value: "inactive" },
      { label: "Archived", value: "archived" },
    ],
  },
  {
    name: "marital_status",
    label: "Marital Status",
    type: "select",
    required: true,
    default: "single",
    gridCol: 2,
    options: [
      { label: "Single", value: "single" },
      { label: "Married", value: "married" },
      { label: "Divorced", value: "divorced" },
    ],
  },
  {
    name: "blood_group",
    label: "Blood Group",
    type: "text",
    required: false,
    gridCol: 2,
  },
  {
    name: "address.country",
    label: "Country",
    type: "text",
    placeholder: "Enter country",
    required: true,
    gridCol: 2,
  },
  {
    name: "address.district",
    label: "District",
    type: "text",
    placeholder: "Enter district",
    required: true,
    gridCol: 2,
  },
  {
    name: "address.province",
    label: "Province",
    type: "text",
    placeholder: "Enter province",
    required: false,
    gridCol: 2,
  },
  {
    name: "address.municipality",
    label: "Municipality",
    type: "text",
    placeholder: "Enter municipality",
    required: false,
    gridCol: 2,
  },
  {
    name: "address.ward_no",
    label: "Ward No",
    type: "number",
    placeholder: "Enter ward number",
    required: false,
    gridCol: 2,
  },
  {
    name: "address.google_map",
    label: "Google Map",
    type: "text",
    placeholder: "Enter google map link",
    required: false,
  },
];
